services:
  db:
    ports:
      - 5441:5432
    container_name: postgre-apidev
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=apidev
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin